name: KernelSU Development Build (Galaxy A50)

on:
  push:

jobs:
  notify:
    name: notify
    runs-on: ubuntu-latest
    steps:
      - name: Send build message to Telegram
        uses: appleboy/telegram-action@master
        env: 
          TELEGRAM_TO: "${{ secrets.TELEGRAM_TO }}"
          TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "🛠️ Build Started for KernelSU 👷"
     
  failure-notification:
    name: Failure Notification
    needs: [build-kernelsu]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Send failure message to Telegram
        uses: appleboy/telegram-action@master
        env: 
          TELEGRAM_TO: "${{ secrets.TELEGRAM_TO }}"
          TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "🛑 Build failed for KernelSU 😞"   
 
  build-kernelsu:
    name: Build KernelSU
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [oneui, aosp]
        enforcing: [e, p]

      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          submodules: true

      - uses: szenius/set-timezone@v1.0
        with:
          timezone: "Asia/Kolkata"

      - name: Export build branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch_name

      - name: Update Debian/Ubuntu Repositories
        run: sudo apt-get update

      - name: Install Debian/Ubuntu dependencies
        run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

      - name: Setup KernelSU
        run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          cd KernelSU
          echo "KSU_VERSION=$(($(git rev-list --count HEAD) + 10200))" >> $GITHUB_ENV
          cd -

      - name: Build Mint kernel
        run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          ./build.sh --kernelsu --automated --device a50 --variant ${{ matrix.variant }} --android 12
          if [[ "${{ matrix.enforcing }}" == "p" ]]; then
            ./build.sh --permissive
          fi

      - name: Prepare release package
        run: |
          mkdir -p ./release
          mv -f `find ./ -iname *.zip` ./release/

      - name: Prepare build config artifact
        run: |
          cp .config ./release/kernel_config_a50_${{ matrix.variant }}-s-k-${{ matrix.enforcing }}.txt

      - name: Upload build to Telegram
        uses: appleboy/telegram-action@master
        env: 
          TELEGRAM_TO: "${{ secrets.TELEGRAM_TO }}"
          TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: " "
          document: ./release/*.zip
          
  ksumanager:
    name: Download ksu latest manager
    needs: [build-kernelsu]
    runs-on: ubuntu-latest
    steps:
     - name: Download ksu latest manager
       id: download-artifact
       uses: dawidd6/action-download-artifact@v2
       with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build-manager.yml
          workflow_conclusion: completed
          branch: main
          event: push
          name: manager
          name_is_regexp: true
          path: ./tmp/
          repo: tiann/KernelSU
          check_artifacts: false
          search_artifacts: false
          skip_unpack: false
          if_no_artifact_found: fail
       
     - name: Upload Manager to Telegram
       uses: appleboy/telegram-action@master
       env: 
          TELEGRAM_TO: "${{ secrets.TELEGRAM_TO }}"
          TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
       with:
         to: ${{ secrets.TELEGRAM_TO }}
         token: ${{ secrets.TELEGRAM_TOKEN }}
         message: "Manager"
         document: ./tmp/manager/*.apk
         if-no-files-found: error       

  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
          delete_workflow_pattern: all
          delete_workflow_by_state_pattern: all
          delete_run_by_conclusion_pattern: all
