name: Fetch and Send Commits to Telegram

on:
  workflow_dispatch:

jobs:
  fetch-commits:
    name: Fetch Commits
    runs-on: ubuntu-latest
    steps:
      - name: Set Time Zone to India
        uses: szenius/set-timezone@v1.0
        with:
          timezone: "Asia/Kolkata"

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: tiann/KernelSU

      - name: Set Up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get Latest Commit
        id: latest-commit
        run: echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Get Commits Since Yesterday
        id: commits
        run: |
          yesterday=$(date -d "yesterday" +%Y-%m-%d)
          git log --format="%s" --since="$yesterday" > commits.txt

      - name: Send Commits to Telegram
        run: |
         echo "Latest Commits in tiann/KernelSU:"
         cat commits.txt | while IFS= read -r line; do
         echo "- $line"
         done | tee commits_message.txt
         cat commits_message.txt | xargs -0 echo | sed 's/"/\\"/g' > escaped_commits.txt
         curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_TO }}" -d "text=$(cat escaped_commits.txt)"
         env:
             TELEGRAM_TO: "${{ secrets.TELEGRAM_TO }}"
             TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"


  delete-workspace:
    name: Delete Workspace
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workspace
        run: rm -rf ${{ github.workspace }}
